# Generated by Django 4.1.3 on 2022-11-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('united_help', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
