# Generated by Django 4.1.3 on 2022-11-07 15:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('united_help', '0003_alter_event_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='manager',
            new_name='owner',
        ),
    ]
