# Generated by Django 4.1.3 on 2022-11-07 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('united_help', '0004_auto_20221107_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='united_help.profile', verbose_name='Owner'),
        ),
    ]
