# Generated by Django 4.1.3 on 2022-11-07 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('united_help', '0005_alter_event_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='parent',
        ),
        migrations.AddField(
            model_name='skill',
            name='parents',
            field=models.ManyToManyField(blank=True, null=True, to='united_help.skill'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='united_help.user', verbose_name='User'),
        ),
    ]
