# Generated by Django 4.1.3 on 2022-11-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('united_help', '0008_profile_is_checked_alter_profile_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_checked',
            new_name='active',
        ),
        migrations.AddField(
            model_name='profile',
            name='users_voted',
            field=models.IntegerField(default=0),
        ),
    ]
