# Generated by Django 4.1.3 on 2022-11-10 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('united_help', '0009_rename_is_checked_profile_active_profile_users_voted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='scores',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='users_voted',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.IntegerField(default=0)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='united_help.profile', verbose_name='Profile')),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='united_help.user', verbose_name='User')),
            ],
        ),
    ]
