# Generated by Django 4.1.3 on 2022-11-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('united_help', '0010_remove_profile_scores_remove_profile_users_voted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
