# Generated by Django 4.1.3 on 2022-11-25 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('united_help', '0011_alter_profile_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happened', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='united_help.event')),
                ('volunteers_attended', models.ManyToManyField(blank=True, related_name='profiles_attended', to='united_help.profile')),
                ('volunteers_subscribed', models.ManyToManyField(blank=True, related_name='profiles_subscribed', to='united_help.profile')),
            ],
        ),
    ]
