# Generated by Django 4.1.3 on 2022-12-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('united_help', '0015_alter_eventlog_log_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='volunteers',
            new_name='participants',
        ),
        migrations.AddField(
            model_name='event',
            name='to',
            field=models.IntegerField(choices=[(1, 'Volunteer'), (3, 'Refugee')], default=1),
        ),
    ]
