# Generated by Django 4.1.3 on 2022-12-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('united_help', '0016_rename_volunteers_event_participants_event_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firebase_tokens',
            field=models.TextField(default=''),
        ),
    ]
