# Generated by Django 4.1.3 on 2023-01-18 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('united_help', '0017_user_firebase_tokens'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voting',
            old_name='scores',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='voting',
            old_name='voting',
            new_name='voter',
        ),
        migrations.AddField(
            model_name='voting',
            name='event',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='united_help.event', verbose_name='Event'),
            preserve_default=False,
        ),
    ]
