# Generated by Django 4.1.3 on 2023-01-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('united_help', '0018_rename_scores_voting_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='following', to='united_help.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.IntegerField(choices=[(0, 'Admin'), (1, 'Volunteer'), (2, 'Organizer'), (30, 'Refugee')]),
        ),
    ]
