# Generated by Django 4.1.3 on 2023-01-19 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('united_help', '0019_user_following_alter_profile_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='enabled',
            new_name='active',
        ),
    ]
