# Generated by Django 4.1.3 on 2023-01-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('united_help', '0022_event_location_lat_event_location_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_display',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_lat',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_lon',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
