# Generated by Django 4.1.3 on 2023-02-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('united_help', '0024_user_facebook_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='facebook_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='firebase_tokens',
            field=models.TextField(blank=True, default=''),
        ),
    ]
